CREATE TABLE Users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    auth_id VARCHAR(255) NOT NULL,
    registration_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE Routines (
    routine_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    date DATE NOT NULL,
    description VARCHAR(255),
    is_completed BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES Users(user_id)
);

CREATE TABLE Exercises (
    exercise_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id INT,
    name VARCHAR(100) NOT NULL,
    muscle VARCHAR(100) NOT NULL,
    FOREIGN KEY (routine_id) REFERENCES Routines(routine_id)
);

CREATE TABLE RoutineExercises (
    routine_exercise_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id INT,
    repetitions INT NOT NULL,
    weight DECIMAL(5, 2) NOT NULL,
    FOREIGN KEY (exercise_id) REFERENCES Exercises(exercise_id)
);